#!/bin/bash
if [ ${#} -ne 2 ]; then
echo "Incorrect amount of arguments" 1>&2
exit 1
fi

res=`mktemp`

while read test
do

if [ ! -r ${test}.in ] || [ ! -r ${test}.out ] || [ ! -f ${test}.in ] || [ ! -f ${test}.out ]; then
echo "Missing .in or .out file" 1>&2
exit 1
fi

if [ -f ${test}.args ]; then

if [ -r ${test}.args ]; then
$2 `cat ${test}.args` < ${test}.in > $res
else
echo "Unreadable Args file" 1>&2
fi

else
$2 < ${test}.in > $res
fi

diff $res ${test}.out > /dev/null
if [ $? -eq 0 ]; then
continue

else
echo ""
echo "Test failed: $test"
echo "Input:"
cat ${test}.in
echo "Expected:"
cat ${test}.out
echo "Actual:"
cat $res
echo ""
fi

done < $1
